import type { Logger, TokenNormalized } from '@terrazzo/parser';

export const PLUGIN_NAME = 'terrazzo-plugin-figma-json';

export const FORMAT_ID = 'figma-json';

export const FILE_PREFIX = `/**
 * Autogenerated by Terrazzo. DO NOT EDIT!
 */`;

/**
 * Token types supported by Figma.
 */
export const SUPPORTED_TYPES = [
  'color',
  'dimension',
  'duration',
  'fontFamily',
  'fontWeight',
  'number',
  'typography',
] as const;

export type SupportedType = (typeof SUPPORTED_TYPES)[number];

/**
 * Token types that are not supported by Figma and will be dropped with a warning.
 */
export const UNSUPPORTED_TYPES = [
  'shadow',
  'border',
  'gradient',
  'transition',
  'strokeStyle',
  'cubicBezier',
] as const;

export type UnsupportedType = (typeof UNSUPPORTED_TYPES)[number];

/**
 * Color spaces that Figma natively supports.
 */
export const FIGMA_COLOR_SPACES = ['srgb', 'hsl'] as const;

export type FigmaColorSpace = (typeof FIGMA_COLOR_SPACES)[number];

/**
 * Figma variable types.
 */
export type FigmaVariableType = 'Color' | 'Number' | 'String' | 'Boolean';

/**
 * Extension keys used by Figma in the $extensions object.
 * Figma uses flat namespaced keys like "com.figma.type", not nested objects.
 */
export interface FigmaExtensionKeys {
  /**
   * Overrides the inferred Figma variable type.
   * Use "boolean" to treat a number token as a boolean (0 = false, non-zero = true).
   * Key: "com.figma.type"
   */
  'com.figma.type'?: 'boolean';
  /**
   * Cross-collection alias data for Figma.
   * Key: "com.figma.aliasData"
   */
  'com.figma.aliasData'?: {
    collection: string;
    mode: string;
  };
}

/**
 * Token extensions object that may include Figma-specific keys.
 */
export type TokenExtensions = FigmaExtensionKeys & {
  [key: string]: unknown;
};

/**
 * Output token structure for Figma-compatible JSON.
 */
export interface FigmaTokenValue {
  /**
   * The DTCG token type.
   */
  $type: string;
  /**
   * The Figma-compatible value.
   */
  $value: unknown;
  /**
   * Optional description.
   */
  $description?: string;
  /**
   * Optional extensions, including Figma-specific ones.
   */
  $extensions?: TokenExtensions;
}

/**
 * Mapping from DTCG types to Figma variable types.
 * Note: Typography is a composite type that splits into sub-tokens, so it doesn't
 * have a direct Figma mapping. The placeholder 'String' is never actually used.
 */
export const DTCG_TO_FIGMA_TYPE_MAP: Record<SupportedType, FigmaVariableType> = {
  color: 'Color',
  dimension: 'Number',
  duration: 'Number',
  fontFamily: 'String',
  fontWeight: 'Number', // Can also be String depending on input value
  number: 'Number', // Can also be Boolean via extension
  typography: 'String', // Composite type - splits into sub-tokens, this is never used
};

/**
 * Context passed to converters.
 */
export interface ConverterContext {
  logger: Logger;
  options: FigmaJsonPluginOptions;
  tokenId: string;
  /**
   * Token extensions, if any. Used to check for Figma-specific type overrides.
   */
  extensions?: TokenExtensions;
  /**
   * All tokens in the design system, used for alias validation.
   */
  allTokens?: Record<string, TokenNormalized>;
  /**
   * Original value before resolution (for checking references in composite types).
   */
  originalValue?: unknown;
  /**
   * Partial alias information for composite types (e.g., typography).
   * Maps sub-property names to their alias target token IDs.
   */
  partialAliasOf?: Record<string, string | undefined>;
}

/**
 * Sub-token information for split composite tokens (e.g., typography).
 */
export interface SubToken {
  /** Suffix to append to parent token ID (e.g., "fontFamily" -> parent.id + ".fontFamily") */
  idSuffix: string;
  /** The $type for this sub-token */
  $type: string;
  /** The converted value */
  value: unknown;
  /** If this sub-property was a reference, the target token ID */
  aliasOf?: string;
}

/**
 * Result returned by a converter.
 */
export interface ConverterResult {
  /** The converted value, or undefined if the token should be skipped. */
  value: unknown;
  /** Whether to skip this token (not include in output). */
  skip?: boolean;
  /** Override the output $type (e.g., fontWeight outputs as 'number' or 'string'). */
  outputType?: string;
  /** Whether this is a split composite token (e.g., typography). */
  split?: boolean;
  /** Sub-tokens for split composite types. */
  subTokens?: SubToken[];
}

/**
 * Color value structure in DTCG format.
 */
export interface DTCGColorValue {
  colorSpace: string;
  components: [number | 'none', number | 'none', number | 'none'];
  alpha?: number | 'none';
}

/**
 * Dimension value structure in DTCG format.
 */
export interface DTCGDimensionValue {
  value: number;
  unit: string;
}

/**
 * Duration value structure in DTCG format.
 */
export interface DTCGDurationValue {
  value: number;
  unit: string;
}

/**
 * Typography value structure in DTCG format.
 */
export interface DTCGTypographyValue {
  fontFamily?: string | string[];
  fontSize?: DTCGDimensionValue;
  fontWeight?: number | string;
  lineHeight?: number | DTCGDimensionValue;
  letterSpacing?: DTCGDimensionValue;
}

/**
 * Options for the Figma JSON plugin.
 *
 * @example
 * // Minimal configuration
 * const options: FigmaJsonPluginOptions = {
 *   filename: "tokens.figma.json",
 * };
 *
 * @example
 * // Full configuration
 * const options: FigmaJsonPluginOptions = {
 *   filename: "design-tokens.figma.json",
 *   exclude: ["internal.*"],
 *   remBasePx: 16,
 *   warnOnUnsupported: true,
 *   tokenName: (token) => token.id,
 *   transform: (token) => undefined,
 *   skipBuild: false,
 * };
 */
export interface FigmaJsonPluginOptions {
  /**
   * Output filename for the Figma-compatible JSON.
   * @default "tokens.figma.json"
   */
  filename?: string;

  /**
   * Glob patterns to exclude tokens from output.
   * @example ["internal.*", "deprecated.*"]
   */
  exclude?: string[];

  /**
   * Custom transform function to override token values before output.
   * Return undefined to use the default transformation.
   */
  transform?: (token: TokenNormalized) => unknown | undefined;

  /**
   * Custom function to control the token name in the output.
   */
  tokenName?: (token: TokenNormalized) => string;

  /**
   * Skip generating the output file.
   * Useful if consuming transforms in another plugin.
   * @default false
   */
  skipBuild?: boolean;

  /**
   * Base pixel value for rem to px conversion.
   * @default 16
   */
  remBasePx?: number;

  /**
   * Whether to log warnings for unsupported token types.
   * @default true
   */
  warnOnUnsupported?: boolean;

  /**
   * Preserve token references (aliases) in the output.
   * When true:
   * - Same-file references use curly brace syntax in $value (e.g., "{dimension.100}")
   * - Cross-file references use resolved $value + com.figma.aliasData extension
   * When false:
   * - All values are fully resolved, no references preserved
   * @default true
   */
  preserveReferences?: boolean;

  /**
   * Split output files based on resolver structure (sets and modifier contexts).
   * When true, outputs separate files for each resolver set and each modifier context.
   * E.g., "primitive.figma.json", "breakpoint-small.figma.json", etc.
   * Only applies when using a resolver file as input.
   * @default false
   */
  splitByResolver?: boolean;
}
